import "./globals.css";
import { Inter } from "next/font/google";
import FormProvider from "./context/form-provider";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Countdown app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="dark" lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <FormProvider>{children}</FormProvider>
        </Providers>
      </body>
    </html>
  );
}
